name: 'dbt_run_metrics'
version: '0.0.0'
config-version: 2
require-dbt-version: ">=1.3.0"

vars:
  run_metrics:
    run_start_history:
    run_end_history:
    rolling_period:
      window: {count: 28, period: day}
      tick:  {count: 1, period: hour}


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start: "{{ dbt_run_metrics.on_run_start() }}"
on-run-end: "{{ dbt_run_metrics.on_run_end(results) }}"
